/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.PrintStream;
import kontroler.Kontroler;

/**
 *
 * @author Jelena
 */
public class FrmGame extends javax.swing.JFrame implements IWindowShowMessages {

    PrintStream izlazniTok;
    BufferedReader ulazniTok;
    String igrac;
    boolean yourTurn;
    private Panel[] panels;

    public FrmGame() {
        initComponents();
        fillPanels();
    }

    public FrmGame(PrintStream izlazniTok, BufferedReader ulazniTok, String igrac, String username) {
        this.panels = new Panel[9];
        this.izlazniTok = izlazniTok;
        this.ulazniTok = ulazniTok;
        this.igrac = igrac;
//        this.username = username;
        if (igrac.equals("x")) {
            yourTurn = true;
        } else {
            yourTurn = false;
        }
        initComponents();
//        Panel p = new Panel(ulazniTok, izlazniTok, this, 1, igrac);
//        jpGame.add(p);
//        panels[0] = p;
//        p.repaint();
//        Panel p1 = new Panel(ulazniTok, izlazniTok, this, 2, igrac);
//        jpGame.add(p1);
//        panels[1] = p1;
//        p1.repaint();
//        Panel p2 = new Panel(ulazniTok, izlazniTok, this, 3, igrac);
//        jpGame.add(p2);
//        panels[2] = p2;
//        p2.repaint();
//        Panel p3 = new Panel(ulazniTok, izlazniTok, this, 4, igrac);
//        jpGame.add(p3);
//        panels[3] = p3;
//        p3.repaint();
//        Panel p4 = new Panel(ulazniTok, izlazniTok, this, 5, igrac);
//        jpGame.add(p4);
//        panels[4] = p4;
//        p4.repaint();
//        Panel p5 = new Panel(ulazniTok, izlazniTok, this, 6, igrac);
//        jpGame.add(p5);
//        panels[5] = p5;
//        p5.repaint();
//        Panel p6 = new Panel(ulazniTok, izlazniTok, this, 7, igrac);
//        jpGame.add(p6);
//        panels[6] = p6;
//        p6.repaint();
//        Panel p7 = new Panel(ulazniTok, izlazniTok, this, 8, igrac);
//        jpGame.add(p7);
//        panels[7] = p7;
//        p7.repaint();
//        Panel p8 = new Panel(ulazniTok, izlazniTok, this, 9, igrac);
//        jpGame.add(p8);
//        panels[8] = p8;
//        p8.repaint();
        jlblUsername.setText(username);

    }

    public void setResult(String res) {
        jlblResult.setText(res);
    }

    public void posaljiPotez(String potez, int pozicija) {
        izlazniTok.println(potez + "/" + pozicija);
        yourTurn = false;
    }

    public void nacrtaj(String potez, int pozicija) {
        panels[pozicija - 1].nacrtaj(potez);
    }

    public boolean isYourTurn() {
        return yourTurn;
    }

    public void setYourTurn(boolean yourTurn) {
        this.yourTurn = yourTurn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGame = new javax.swing.JPanel();
        jlblUsername = new javax.swing.JLabel();
        jlblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setResizable(false);

        jpGame.setLayout(new java.awt.GridLayout(3, 3));

        jlblUsername.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGame, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblUsername)
                    .addComponent(jlblResult))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jlblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblResult)
                .addGap(27, 27, 27)
                .addComponent(jpGame, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblResult;
    private javax.swing.JLabel jlblUsername;
    private javax.swing.JPanel jpGame;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showMessage(String title, String message) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void showErrorMessage(String title, String message) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void showQuestionMessage(String title, String message) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void fillPanels() {
        panels = new Panel[9];
        for (int i = 0; i < 9; i++) {
            Panel p = new Panel((i + 1));
            jpGame.add(p);
            panels[1] = p;
            p.repaint();
        }
        jlblUsername.setText(Kontroler.getInstance().getPlayer().getUsername() + " " + igrac);
    }

}
