/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.PrintStream;

/**
 *
 * @author Jelena
 */
public class Game extends javax.swing.JFrame {

    PrintStream izlazniTok;
    BufferedReader ulazniTok;
    String igrac;
    boolean yourTurn;
    Panel[] paneli = new Panel[9];
    String username;

    public Game(PrintStream izlazniTok, BufferedReader ulazniTok, String igrac, String username) {
        this.izlazniTok = izlazniTok;
        this.ulazniTok = ulazniTok;
        this.igrac = igrac;
        this.username = username;
        if (igrac.equals("x")) {
            yourTurn = true;
        } else {
            yourTurn = false;
        }
        initComponents();
        Panel p = new Panel(ulazniTok, izlazniTok, this, 1, igrac);
        jPanel1.add(p);
        paneli[0] = p;
        p.repaint();
        Panel p1 = new Panel(ulazniTok, izlazniTok, this, 2, igrac);
        jPanel1.add(p1);
        paneli[1] = p1;
        p1.repaint();
        Panel p2 = new Panel(ulazniTok, izlazniTok, this, 3, igrac);
        jPanel1.add(p2);
        paneli[2] = p2;
        p2.repaint();
        Panel p3 = new Panel(ulazniTok, izlazniTok, this, 4, igrac);
        jPanel1.add(p3);
        paneli[3] = p3;
        p3.repaint();
        Panel p4 = new Panel(ulazniTok, izlazniTok, this, 5, igrac);
        jPanel1.add(p4);
        paneli[4] = p4;
        p4.repaint();
        Panel p5 = new Panel(ulazniTok, izlazniTok, this, 6, igrac);
        jPanel1.add(p5);
        paneli[5] = p5;
        p5.repaint();
        Panel p6 = new Panel(ulazniTok, izlazniTok, this, 7, igrac);
        jPanel1.add(p6);
        paneli[6] = p6;
        p6.repaint();
        Panel p7 = new Panel(ulazniTok, izlazniTok, this, 8, igrac);
        jPanel1.add(p7);
        paneli[7] = p7;
        p7.repaint();
        Panel p8 = new Panel(ulazniTok, izlazniTok, this, 9, igrac);
        jPanel1.add(p8);
        paneli[8] = p8;
        p8.repaint();
        jLabel2.setText(username);

    }
    public void setResult(String res){
        jLabel3.setText(res);
    }

    public void posaljiPotez(String potez, int pozicija) {
        izlazniTok.println(potez + "/" + pozicija);
        yourTurn = false;
    }

    public void nacrtaj(String potez, int pozicija) {
        paneli[pozicija - 1].nacrtaj(potez);
    }

    public boolean isYourTurn() {
        return yourTurn;
    }

    public void setYourTurn(boolean yourTurn) {
        this.yourTurn = yourTurn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic-Tac-Toe");
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
