/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jelena
 */
public class Panel extends javax.swing.JPanel implements MouseListener {

    BufferedReader ulazniTok;
    PrintStream izlazniTok;
    Game frmGlavna;
    int pozicija;
    String potez;
    String igrac;
    boolean odigrao = false;

    public Panel(BufferedReader ulazniTok, PrintStream izlazniTok, Game frmGlavna, int pozicija, String potez) {
        initComponents();
        setPreferredSize(new Dimension(30, 30));
        this.ulazniTok = ulazniTok;
        this.izlazniTok = izlazniTok;
        this.frmGlavna = frmGlavna;
        this.pozicija = pozicija;
        this.potez = potez;
        this.igrac = null;
        addMouseListener(this);
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.fillRect(0, 0, getWidth(), getHeight());
        Graphics2D g2d = (Graphics2D) g;
        int r = 80;
        g2d.setStroke(new BasicStroke(3));

        g.setColor(Color.white);
        if (pozicija == 1 || pozicija == 2 || pozicija == 4 || pozicija == 5) {
            g.drawLine(getWidth(), 0, getWidth(), getHeight());
            g.drawLine(0, getHeight(), getWidth(), getHeight());
        } else {
            if (pozicija == 3 || pozicija == 6) {
                g.drawLine(0, getHeight(), getWidth(), getHeight());
            } else {
                if (pozicija == 7 || pozicija == 8) {
                    g.drawLine(getWidth(), 0, getWidth(), getHeight());
                }
            }
        }
        if (odigrao) {
            if (potez.equals("x")) {
                g2d.drawLine(10, 10, getWidth() - 10, getHeight() - 10);
                g2d.drawLine(10, getHeight() - 10, getWidth() - 10, 10);
            } else {
                g2d.drawOval((getWidth() - r) / 2, (getHeight() - r) / 2, r, r);
            }
        }
        if (igrac != null) {
            if (igrac.equals("x")) {
                g2d.drawLine(10, 10, getWidth() - 10, getHeight() - 10);
                g2d.drawLine(10, getHeight() - 10, getWidth() - 10, 10);
            } else {
                g2d.drawOval((getWidth() - r) / 2, (getHeight() - r) / 2, r, r);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void mouseClicked(MouseEvent e) {
        if (frmGlavna.yourTurn && !odigrao && igrac == null) {
            odigrao = true;
            repaint();
            frmGlavna.posaljiPotez(potez, pozicija);

        }
    }

    public void nacrtaj(String potez) {
        igrac = potez;
        frmGlavna.yourTurn = true;
        repaint();
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
